### ISSUE TITLE
Incorrect field in metadata

### ISSUE THREAD

**Issue by aidanheerdegen** [COSIMA/01deg_jra55_iaf#9]
The `metadata.yaml` file has a field `note`, should be `notes`:

https://github.com/COSIMA/01deg_jra55_iaf/blob/01deg_jra55v140_iaf/metadata.yaml#L12

The supported fields for the explorer are listed here:

https://github.com/COSIMA/cosima-cookbook/blob/master/cosima_cookbook/database.py#L54

**Comment by aekiss** [comment]
Thanks @aidanheerdegen, good catch - is the content of the notes field OK or should it be a list?

**Comment by aidanheerdegen** [comment]
Not a list. Is just sucked in as a blob of text

**Comment by aekiss** [comment]
OK ta. I've fixed it here and also in all the ak-dev configs.
